---
- name: Pulling From Docker Image
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: rudranshd/calculator_app:latest
        source: pull
    - name: Start docker container
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator rudranshd/calculator_app
